### ISSUE TITLE
issue with incrementing counts in gpu worker

### ISSUE THREAD

**Issue by tmills** [tmills/uhhmm#41]
Quits during d=2 run:

Traceback (most recent call last):
  File "scripts/uhhmm-trainer.py", line 86, in <module>
    main(sys.argv[1:])
  File "scripts/uhhmm-trainer.py", line 66, in main
    (samples, stats) = uhhmm.sample_beam(word_seq, params, lambda x: io.write_output(x, None, config, pos_seq), lambda x: io.checkpoint(x,config), working_dir, pickle_file, gold_seq)
  File "/home/tmill/Projects/gpu-uhhmm/scripts/uhhmm.py", line 313, in sample_beam
    increment_counts(parse.state_list, ev_seqs[ parse.index ], models)
  File "/home/tmill/Projects/gpu-uhhmm/scripts/uhhmm.py", line 952, in increment_counts
    assert prev_depth == cur_depth
AssertionError

**Comment by lifengjin** [comment]
This one was seen by Cory as well. However I could not repro it with about 150 iterations with depth =2 and 30 iterations with depth = 3. How did you get it?

**Comment by tmills** [comment]
5/5/15, d=2, 4 procs. I accidentally exited out of that screen session but
it quit at around 17 iterations I believe. I'm trying to repro now.

**Comment by vkrakovna** [comment]
I also sometimes get an assertion fail after the same call to
increment_counts() in uhhmm.py (in the parse loop, line 311). The maximum
POS tag in hid_seqs becomes inconsistent with models.pos.dist.shape,
triggering the assert in max_state_check().

**Comment by lifengjin** [comment]
I ran the system on OSC with depth =2 5,5,15 for 140 iterations without any issue. Log probs went from -17912 to -15566. Maybe something to do with software versions?

**Comment by tmills** [comment]
Yeah in my reproduction its run 650 iterations with no issue. Let's leave
it open so we have a record of it.
Tim

**Comment by tmills** [comment]
On the wsj20 corpus with 5/5/20 I'm seeing this issue very frequently. I'm also seeing issues with probability calculations, though it doesn't look related:
ERROR:root:Sentence 9361 had positive log probability 117324.015625
ERROR:root:Sentence 9363 had positive log probability 117324.367188
ERROR:root:Sentence 9391 had positive log probability 117325.234375

**Comment by tmills** [comment]
Tried varying parameters. With 5/5/20 and depth 2 model on simple wiki d=1 data no issues. However none of the samples actually require the second level of depth.

With 5/5/20 and depth 2 model on wsj20 tons of issues. It unfortunately was hard to run long enough to get any samples to see if it's using depth 2.

**Comment by lifengjin** [comment]
How frequent?

**Comment by lifengjin** [comment]
Wrong button.

**Comment by tmills** [comment]
It will usually run for only one or two iterations before it happens.

**Comment by lifengjin** [comment]
OK I can repro the assertion error. Will look into that. Seems to be related to big g?

On the demo data I ran 1800 iterations with 5/5/10 d2 model, and observed some d2 analyses.

**Comment by lifengjin** [comment]
The problem lies here:

```
        for ind in np.where(self.dyn_prog[t,:] != 0.0)[0]:                     
            self.dyn_prog[t,ind] *= trans_slice[ind]

        normalizer = self.dyn_prog[t,:].sum()
```

The GPU version just multiplies dyn_prog[t, :] with trans_slice, but in the CPU version it is a loop. This prevents the case where trans_slice is all zero. Can you help me understand this a bit more, Tim? Under what circumstance the trans probs from one state to all states are zero?

**Comment by tmills** [comment]
trans_slice = pi[:, sample_t] -- the probabilities from all previous states at time t into the most recently sampled state at t+1.
So if trans_slice is all zeros that means there is no transition into a state s_{t+1} that has non-zero probability. While it might be possible that some state cannot be reached, it would have to be an impossible state, and that should never have been sampled in the first place.

**Comment by tmills** [comment]
Trying this patch:

```
diff --git a/gpusrc/State.cu b/gpusrc/State.cu
index 098a025..5cc64f5 100644
--- a/gpusrc/State.cu
+++ b/gpusrc/State.cu
@@ -21,7 +21,7 @@ int State::max_awa_depth(){
         return -1;
     }
     // cout << "getting in second loop" << endl;
-    for (int d = 1; d <= depth; d++) {
+    for (int d = 1; d < depth; d++) {
         if (b[d] == 0){
             return d - 1;
         }
```

so far so good but I'll let it try to run for > 10 or so iterations to make sure.

**Comment by tmills** [comment]
Pushed the fix -- made it 10 iterations without error message. If it makes it to tomorrow morning I'll close the issue.

**Comment by lifengjin** [comment]
I will try too. I also pushed some fix to an issue I found when I was trying to debug this.

**Comment by lifengjin** [comment]
Still seeing it.

**Comment by tmills** [comment]
Error message:

```
ERROR:root:This parse is bad:
ERROR:root:The sentence is 294 2861 5360 13622 141 9669 17
ERROR:root:-/-::ACT0/AWA0:POS7 +/-::ACT5/AWA1:POS3 -/-::ACT2/AWA4:POS11 -/-::ACT1/AWA4:POS9 -/-::ACT5/AWA4:POS11 +/+::ACT5/AWA4:POS1 +/-::ACT3/AWA6;ACT3/AWA0:POS8
ERROR:root:The index is 19136
```

Looks like it sampled a depth 2 state at the last time step -- this should not be allowed. I'll look for the check in the gpu code.

**Comment by tmills** [comment]
OK the AWA state at the last time step is 0 -- so the depth function checks that for depth, it should only be 0 if there is nothing there. So that means the model is illegally assigning some positive probability to b=0. I'll check back into the model compiler to see if I can find any issue.

Temporary fix is to force a and b to both be 0. Same error may pop up occasionally but less rare, then I'll keep looking for the root. Might be the indexer.

**Comment by lifengjin** [comment]
I was seeing this:

```
ERROR:root:This parse is bad:
ERROR:root:The sentence is 1735 103 1736
ERROR:root:-/-::ACT0/AWA0:POS10 +/-::ACT3/AWA4:POS1 +/+::ACT3/AWA3:POS13
ERROR:root:The index is 320
```

which indicates something is off in the depth calculation? The parse looks fine.

**Comment by tmills** [comment]
What is depth set to for that run?

**Comment by lifengjin** [comment]
Seems OK with the new fix now.

**Comment by tmills** [comment]
```
ERROR:root:This parse is bad:
ERROR:root:The sentence is 5702 21 9 2862 3261 49 9 4041 3336 56 12113 295 278 11 871 11 9 16421 17
ERROR:root:-/-::ACT0/AWA0:POS6 +/-::ACT3/AWA1:POS7 -/-::ACT5/AWA5:POS13 +/-::ACT5/AWA5;ACT2/AWA5:POS4 -/+::ACT5/AWA3:POS9 -/-::ACT3/AWA3:POS2 -/-::ACT4/AWA4:POS7 -/-::ACT3/AWA1:POS3 -/-::ACT4/AWA4:POS2 -/-::ACT3/AWA3:POS7 +/+::ACT3/AWA1:POS9 +/+::ACT3/AWA3:POS11 -/-::ACT2/AWA4:POS8 +/+::ACT2/AWA5:POS5 -/-::ACT5/AWA2:POS2 -/-::ACT3/AWA2:POS6 -/-::ACT3/AWA1:POS7 +/+::ACT3/AWA4:POS11 -/-::ACT4/AWA5:POS12
ERROR:root:The index is 20109
Traceback (most recent call last):
  File "/home/tmill/Projects/uhhmm/scripts/uhhmm.py", line 322, in sample_beam
    increment_counts(parse.state_list, ev_seqs[ parse.index ], models)
  File "/home/tmill/Projects/uhhmm/scripts/uhhmm.py", line 964, in increment_counts
    assert prev_depth == cur_depth, "Found a transition where prev_depth=%d and cur_depth=%d, depth=%d and index=%d/%d" % (prev_depth, cur_depth, depth, index, len(sent) )
AssertionError: Found a transition where prev_depth=1 and cur_depth=0, depth=2 and index=2/19
```

will take a look.

**Comment by tmills** [comment]
Actually I'm not sure my compile worked right, I'll retry.

**Comment by tmills** [comment]
I rigged the assert to recalculate the depth and have it print when it does. Looks like in this example even though it printed one level of depth the b vector has a non-zero element where a has a zero.

```
A vector is: 4::0
B vector is: 5::0
Checking b at depth 1
b[1] = 0 so i'm returning
A vector is: 1::0
B vector is: 4::1
Checking b at depth 1
Did not find any zeros so returrning 1
ERROR:root:This parse is bad:
ERROR:root:The sentence is 30 9 6461 83 823 7418 3 85 9 7419 83 2395 695 49 655 1605 17
ERROR:root:-/-::ACT0/AWA0:POS1 +/-::ACT2/AWA2:POS7 -/-::ACT4/AWA2:POS7 +/+::ACT4/AWA5:POS2 +/+::ACT1/AWA4:POS15 -/-::ACT2/AWA2:POS7 +/+::ACT2/AWA4:POS12 -/-::ACT5/AWA1:POS7 -/-::ACT2/AWA1:POS2 +/+::ACT2/AWA4:POS9 -/-::ACT2/AWA5:POS12 -/-::ACT4/AWA4:POS14 -/-::ACT4/AWA3:POS8 -/-::ACT3/AWA3:POS11 -/-::ACT1/AWA5:POS4 -/-::ACT1/AWA1:POS11 -/-::ACT4/AWA5:POS13
ERROR:root:The index is 3166
Traceback (most recent call last):
  File "/home/tmill/Projects/uhhmm/scripts/uhhmm.py", line 322, in sample_beam
    increment_counts(parse.state_list, ev_seqs[ parse.index ], models)
  File "/home/tmill/Projects/uhhmm/scripts/uhhmm.py", line 968, in increment_counts
    assert prev_depth == cur_depth, "Found a transition where prev_depth=%d and cur_depth=%d, depth=%d and index=%d/%d, prev_state=%s, cur_state=%s, prev_depth_recalc=%d, cur_depth_recalc=%d" % (prev_depth, cur_depth, depth, index, len(sent), prevState.str(), state.str(), prevState.max_awa_depth_err(), state.max_awa_depth_err() )
AssertionError: Found a transition where prev_depth=0 and cur_depth=1, depth=2 and index=4/17, prev_state=+/+::ACT4/AWA5:POS2, cur_state=+/+::ACT1/AWA4:POS15, prev_depth_recalc=0, cur_depth_recalc=1
```

**Comment by tmills** [comment]
To debug this I created depth_check() methods in the python and c++ versions of State that compares active and awaited depths and call it at various points. It fires only when the depths don't match. It doesn't get called by the c++ code but then it does by the python code, so it seems that something is getting messed up in the conversion from a c++ structure to a python one. I've pushed this debugging code if you want to try it.

**Comment by tmills** [comment]
```
-           if (dart != (*sum_dict)[dart_target]){
+           if (dart != (*sum_dict)[dart_target] && v[dart_target] != 0){
```

with this change i was able to get it to run overnight for 83 iterations. Doesn't address the underlying issue but will allow me to proceed with some experiments hopefully. Will see if it gets through the day today.

**Comment by lifengjin** [comment]
I think it is smart that the check is done on v, not on sum_dict, as the error is introduced in the prefix sum as discussed with William today. I think this should solve it.

**Comment by tmills** [comment]
I still get sentences with log prob > 0 but I think that is sentences with a single word. I have removed them from my dataset since it's not really "parsing" if it's one word.
